services:
  auth:
    build: services/auth-service
    ports:
      - "5001:5000"
    env_file:
      - ./services/auth-service/.env

  gateway:
    build: ./gateway
    ports:
      - "4000:5000"
    depends_on:
      - auth
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
